### ISSUE TITLE
Формулируем концепт с учетом дальнейшей интеграции с Operation mode на Minecraft

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/Gamedev#1]
Формулируем концепт с учетом дальнейшей интеграции с Operation mode на Minecraft

Результатат итерации по задаче:
- гуглодок концепта
- дорисованную [доску](https://github.com/u-transnet/GameStratMode/projects) (это роадмап и есть) 
- гуглокнига с фин-потоком для комментариев и дополнений. 

Cсылки на концепт и книгу прям в комментах указываем в кач-ве результата.

**Comment by cptn-solo** [comment]
@Arteg0r 
BLOCK #22785994
TRANSFER |  
From | arteg0r
To | utd-architect-game
Quantity | 210.00000 UTDEV.SKILL

> итерацию смотрим утром в субботу, 23 декабря 2017

**Comment by Arteg0r** [comment]
- [Концепция игры TRANSNET SPACE](https://docs.google.com/document/d/11Sk2VMlI0M9kjpFsFv1ZITH34eyoFcKSbHnLl5fOxFE/edit?usp=sharing)

- [Роадмап](https://github.com/u-transnet/Gamedev/projects/1) 

- [Бюджет gamedev направления](https://docs.google.com/spreadsheets/d/17fOWK0LxWQHG8FAjshb8tqj10NYhc5Kip23snnNRGTI/edit?usp=sharing)

**Comment by cptn-solo** [comment]
@Arteg0r по бюджету - давай раскидаем на полгода финансовый поток по аналогии с основным бюджетом - и закрываем итерацию, уходим на следующую

**Comment by alecvert** [comment]
@Arteg0r @kkrupovich с документом и дорожной картой подробно ознакомился. Весьма положительное мнение. Все обсуждения и комментарии к документу чуть позже. В начале ждем бюджет для того, чтобы запустить данное направление.

**Comment by cptn-solo** [comment]
@Arteg0r @alecvert 

BLOCK #22965032
TRANSFER |  
From | utd-architect-game
To | arteg0r
Quantity | 210.00000 UTDEV

Закрываем, уходим на #2
