### ISSUE TITLE
StarWay: Asteroid Rush - итерация 2 и работа над KryptoProgressorom

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#10]
@Arteg0r @Dvarnrock 

По итогам обсуждений концепции Asteroid Rush (https://github.com/u-transnet/Gamedev/issues/8)  начал новую итерацию

По итогам итерации будет создано новый документ с более подробным описанием отдельных функциональных блоков игры, их взаимодействием, пользовательскими сценариям и первичное предложение об объемах разработки.

Так же совместно с @Dvarnrock доводим до ума питч по третьему концепту, временно получивший дополнительное название Krypto Progressor

На выходе:

- Расширенный Концепт Документ по Asteroid Rush (будет прилинкован по окончании)
- Завершен, совместно с @Dvarnrock питч по Крипто ПРогрессорам

данная итерация идет с 6 по 8 февраля включительно. Рабочих дней - 3.

**Comment by cartoonka** [comment]
BLOCK #24217233

From | alexei-postnikov
To | utd-gamedesign
Quantity | 300.00000 UTDEV.SKILL
Fee | 0.01890 BTS

**Comment by cartoonka** [comment]
Иетарция завершена не совсем как ожидалось, по результатам обсуждений решено эволюционировать в совместную концепцию с предложением от жены Паши, посмотреть можно по [этой ссылке](https://docs.google.com/document/d/1eIvwhZqnrY0YmYYj8rpTgPreAbwquhtqWrcgqN0EDKY/edit?usp=sharing) 

Итерация закрыта и перетекла в следующую. @Arteg0r

**Comment by Arteg0r** [comment]
BLOCK #24368931

TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 300.00000 UTDEV

@cartoonka, спасибо!

**Comment by cptn-solo** [comment]
@cartoonka @Arteg0r @Dvarnrock @alecvert @nat-brit @Dima-Iron друзья, не могу не процитировать, это **просто прекрасно** :
> Представьте, что будущее уже наступило. Что Земля – планета победившего крипто-коммунизма. Государства – это лишь сложившиеся исторически границы между странами, определяющими культурные различия между людьми, и свои дальнейшие цели человечество определяет благодаря открытой и справедливой системе блок-чейна.
	И этот путь – покорение космического пространства.
	Вся планета, как единый живой организм, поставила перед собой глобальную цель – построить на орбите между Землей и Марсом космическую станцию, целый новый дом, откуда уже в недалеком будущем в разные концы вселенной отправятся первые звездолеты.
