### ISSUE TITLE
Доработка питчей отобранных идеи по результатам обсуждений

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#11]
@Arteg0r @cartoonka 

Продолжение предыдущей [задачи](https://github.com/u-transnet/Gamedev/issues/9)

- Продолжаем доработку отобранных концептов с учетом новых данных.
- Подготовка к предварительному совещанию со смежниками.
- Подготовка списка вопросов по концептам для обсуждения.

В результате появится черновик концепта SkyWay: Cities Mk2.
Сформулием идеи и пополним список вопросов к обсуждению 12.02 со смежниками.

Время на задачу 9,02[]12.02

**Comment by pkondrashov-ms** [comment]
Block #24358594
From | pkondr1979
To | utd-gamedesign
Quantity | 200.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
В пятницу 9.02 провели две встречи (одну не по плану), на которых обговорили концепт CryptoProgressor. В результате итерации концепт отправился на полку, как слишком сложная идея для реализации, а также как не слишком перспективная с точки зрения разработки геймплея.

Отложенный концепт [тут](https://docs.google.com/document/d/1pdLjQHMfRVJNGcGyRHdzZ8QnykKtZmnu5DIU0HLWRpQ/edit).


В понедельник 12.09 шла работа над "форком" концепта SkyWay: Cities. Провели планирование и встречу для выявления новых (и пропущенных) идей. В результате решено было вернутся к первоначальной задумке craft survival game и взять ее в разработку со вторника.

Текущий черновик концепта SkyWay: Cities Mk 2 [тут](https://docs.google.com/document/d/1K1J0giDMHHYFjpNrwP8tHI4pmpAIsX5l83wqqHhZdDU/edit#heading=h.l8ez2mnqs1jv).


 @Arteg0r  Задачу закрываю.

**Comment by Arteg0r** [comment]
BLOCK #24427570


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 200.00000 UTDEV

Спасибо, @Dvarnrock !
