### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 3 и работа над возможными питчами. 

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#12]
@Arteg0r @Dvarnrock В продолжении работы над Asteroid Rush и задачи [номер 10](https://github.com/u-transnet/Gamedev/issues/10)  решено объединить концепцию AsteroidRush с концепцией про более миролюбивую игру по мотивам [вот этого документа](https://docs.google.com/document/d/1eIvwhZqnrY0YmYYj8rpTgPreAbwquhtqWrcgqN0EDKY/edit) 

На выходе ожидается объединенный документ с описанием развития как в боевом варианте, так и в миролюбивом кооп сообществе

Итерация с 9 по 12 февраля включительно, рабочих дней 2.

Обсуждение результата - на брейншторме 13 февраля в дискорде.

**Comment by cartoonka** [comment]
BLOCK #24361617
From | alexei-postnikov
To | utd-gamedesign
Quantity | 200.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
@cartoonka @Dvarnrock это "тот самый документ", фидбэк от внешних участников проекта? ;)

**Comment by cartoonka** [comment]
насколько я знаю - да :)

**Comment by cartoonka** [comment]
Итерация плавно перетекает в следующую, так как по результатам общение с Костей и Наташей появились новые идеи и мысли какие и как механики описать и итмсплементировать.

Данную итерацию закрываю без ссылки на документ, так как сейчас документ в разобранном виде.

@Arteg0r

**Comment by Arteg0r** [comment]
BLOCK #24427654


TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 200.00000 UTDEV

Спасибо, @cartoonka !
