### ISSUE TITLE
Работа над концептом SkyWay: Pioneers + другие текущие задачи (в комментариях)

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#13]
@Arteg0r @cartoonka 

Предыдущая [задача](https://github.com/u-transnet/Gamedev/issues/11).

В данной итерации ведется работа над концептами SkyWay: Cities Mk2 и SkyWay: Pioneers (craft survival game).

А также по мере возникновения: встречи со смежниками, брейнштормы, обсуждения черновиков и новых концепций.

В результате будет принято решение по концепту SkyWay: Cities Mk2 
Появится представление и краткий концепт-документ SkyWay: Pioneers

Сроки: 13.02 - 16.02

**Comment by pkondrashov-ms** [comment]
Block #24392115
Transfer |  
From | pkondr1979
To | utd-gamedesign
Quantity | 400.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
@Arteg0r @Dvarnrock @cartoonka парни, спасибо за репозиторий. Очень грамотно раскладываете задачи и хорошо показываете ход работы.

**Comment by pkondrashov-ms** [comment]
В результате:

1) Концепцию Cities Mk2 после обсуждения отложили на полку - не влезает основная идея развития сети SkyNet и Transnet в мобильный геймплей на 15 минут за прохождение.

Концепт развиваться не будет, почитать можно тут:
https://docs.google.com/document/d/1K1J0giDMHHYFjpNrwP8tHI4pmpAIsX5l83wqqHhZdDU/edit

2) Краткий концепт SkyWay: Pioneers прошел обсуждение, принят и направлен в дальнейшую разработку:
https://docs.google.com/document/d/1Ih58xpl-Zp2yM3VJTXUwQkkG59Ovh1HqRY00Gbz4u1E/edit#heading=h.tp97zwdfohq

@Arteg0r 
Задачу можно закрывать.

**Comment by cptn-solo** [comment]
Концепт Pioneers поддерживаю, дадите доступ к доку - смогу в паре мест оставить фитбэк, если это уместно - основное - лучше не использовать термин Share - во-первых он дискредитирован, во-вторых - экономика будущего, какой ее видит блокчейн-сообщество (как минимум в моем лице) вся об этом, о разделяемом доступе ко всему, поскольку всё есть общий продукт и процесс - а значит это одно из «подразумеваемых» понятий, его нет смысла дополнительно вербализовать. Я не говорю, показывая на свой дом, что это моя половина совместного владения с женой, или треть, если считать ребенка - это просто мой дом :)) как-то так

**Comment by Arteg0r** [comment]
@kkrupovich Выдал доступ

**Comment by Arteg0r** [comment]
BLOCK #24582761

TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 400.00000 UTDEV

@Dvarnrock Спасибо!
