### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 4 и работа над новым питчем SkyWay Planets

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#14]
@Arteg0r @Dvarnrock Продолжение работы над концептом AsteroidRush как следствие задачи (https://github.com/u-transnet/Gamedev/issues/12) и по итогам общения с Костей и Наташей 13 февраля.

- Навыходе ожидается расширенный концепт документ с кооперативным режимом и боевым режимом и идеями по имплементации токенов в разные модули игры.

Вторая часть работы - создание питча SkyWay Planets, появившегося в результате брейншторма 14 февраля, люблю эту идею!

- На выходе 2-3 страничный питч документ с описанием ключевой механики и как мы это будем реализовывать.

Итерация идет с 13 по 16 февраля включительно, рабочих дней - 4.

**Comment by cartoonka** [comment]
BLOCK #24420413
TRANSFER |  
From | alexei-postnikov
To | utd-gamedesign
Quantity | 400.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
Итерация плавно перетекла в следующую, попутно возникшие вопросы и проблемы, которые слегка задерживают появление нормального концептдока

Asteroid Rush:

- одна из главных проблем, это понимание какой геймплея сделать ключевым для "мирной" добычи полезных ископаемых. По результатам брейншторма 19-02-2018 выбрано 4 гейммеханики для проверки:

1. Механика minesweaper (Сапёр)
2. Механика три-в-ряд (Match3)
3. Механика Cube Clicker
4. Бомберман

Прогресс развития концепдока следует [смотреть в борде](https://realtimeboard.com/app/board/o9J_kzr93Fs=/) в Realtimeboard
 
SkyWay Planets:

Ключевой проблемой питча оказались слишком большие амбиции - сделать многопользовательскую стратегию в космосе с p2p экономикой и процедурногенерируемыми мирами - слишком гигантская задача.

По итогам мини брейншторма 19-02-2018 решено:

1. Игру делать синглплеерной
2. Ограничить количество планет (локаций)
3. Токенизацию ограничить тем, что по прохождению игры пользователь будет получать токены, которые можно использовать в рамках других игр и проектов UT

Прогресс проекта наблюдаем [тут](https://realtimeboard.com/app/board/o9J_kzruL0M=/)

Итерацию можно закрывать.

**Comment by cptn-solo** [comment]
@cartoonka на самом деле мы и не преследуем цели построения законченной игры - это открытый код, сообщество может скоординировать такой проект, которого заслуживает ;)

**Comment by Arteg0r** [comment]
BLOCK #24596227


TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 400.00000 UTDEV

Спасибо!
