### ISSUE TITLE
Расширенный концепт SkyWay: Pioneers

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#15]
@Arteg0r @cartoonka 

Предыдущая [задача](https://github.com/u-transnet/Gamedev/issues/13).

В данной итерации:
1) Разработка расширенного концепта проекта SkyWay: Pioneers, включающего в себя разделы по CoreLoop и "15 минут геймплея",
2) Созвоны по SkyWay: Planets + Asteroids, созвоны со смежниками, the last брейншторм.

Ожидаемые результаты: Расширенный концепт SkyWay: Pioneers.
Время на задачу: 19.02 - 22.02 (включительно)

**Comment by pkondrashov-ms** [comment]
Block #24561520
Transfer |  
From | pkondr1979
To | utd-gamedesign
Quantity | 400.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
По результатам итерации:

1) [Тут](https://realtimeboard.com/app/board/o9J_kzqgWFM=/)  появились Core Loop геймплея и экономики проекта SkyWay: Pioneers
2) В ходе переключения задач появилось небольшое видение мини-игры для проекта Asteroids ([вот один из вариантов](https://docs.google.com/document/d/1Q3ZXdwa7Pqz8nfdytS83mqCo4NexOH3Lah2zgeZpdY8/edit))
3) Провели рабочее обсуждение проекта Planets, скорректировали видение к питчу.
4) Получили от Константина кусочек информации об устройстве "токенизированной экономики" Transnet.

@Arteg0r 
Данную задачу можно закрывать.

**Comment by Arteg0r** [comment]
BLOCK #24788020


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 400.00000 UTDEV

@Dvarnrock Спасибо!
