### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 5 и работа над примерами геймплея для SkyWay Planets

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#16]
@Arteg0r @Dvarnrock Продолжение развития концепта Asteroid Rush и развитие питча SkyWay Planets в продолжение итерации (https://github.com/u-transnet/Gamedev/issues/14)

**Asteroid Rush**

В данной итерации запланировано прописывание общей канвы сюжета и клчевые этапов игры, задачи которые игрок решает в каждом этапе игры, зачем и почему так сделано

на выходе - борда в рилтаймбор пополнится общим таймлайном для игры, наконец появятся фрэймы описывающие ключевые события, деятельность и задачи в этапах "Луна" "Астероиды" и описаны примерные ключевые завязки трех сюжетных дополнений на будущее.

**SkyWay Planets**

По итогам брейншторма 20-02-2018 зафиксирован питч документ в новой ипостаси (сингл плеерная сюжетная стратегия, описывающая миссию UT по выводу человечества в космос запределы Земли)

Питч документ (в рабочем состоянии) [тут](https://docs.google.com/document/d/1XtUNkd6IhNToMb0_FU5IOTTuqDI5TosfSDZaHR8f2Uw/edit?usp=sharing)

В конце итерации будет предложено несколько описаний геймплея от меня и Паши примеры дерева технологий, которое было бя для нас полезно.

Длительность итерации - 19-22 февраял включительно, рабочих дней - 4.

**Comment by cartoonka** [comment]
BLOCK #24590186
TRANSFER |  
From | alexei-postnikov
To | utd-gamedesign
Quantity | 400.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
Итерация завершилась на стадии обсуждения общей структуры движения игрока по "истории игры" и обсуждением какие мини игры использовать в разных ситуациях, Результаты можно смотреть на борде в realtimeboard.
@Arteg0r задачу можно закрывать.

**Comment by Arteg0r** [comment]
BLOCK #24820793


TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 400.00000 UTDEV
