### ISSUE TITLE
Финализация питчей

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#17]
@Arteg0r @cartoonka 

Предыдущая [задача](https://github.com/u-transnet/Gamedev/issues/15).

По результатам данной итерации:
1. Написана глава "1 час геймплея" для проекта SkyWay: Pioneers.
2. Предварительный сценарий 2-й кампании для Planets.
2. Обсуждены и утверждены финальные питчы SkyWay: Asteroid Rush, Pioneers и Planets

Срок: 26.02-1.03

**Comment by pkondrashov-ms** [comment]
Block #24759921
From | pkondr1979
To | utd-gamedesign
Quantity | 400.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
@Arteg0r 

Внезапна! После совещания 28.02 решено создать питч по новому AR проекту! )

**Comment by pkondrashov-ms** [comment]
По результатам:
Глава "Час геймплея"для SkyWay Pioneers [тут](https://docs.google.com/document/d/1VgbktFZemuXWkKYAef3Zk1CmT2OnBPxugm1ABOwVCQI/edit). 

Вместо предварительного сценария появился рабочий черновик питча новой идеи [SkyWay Quantum Pioneers](https://docs.google.com/document/d/13RVhQvV2kJXKcIuNSG_dAOkUffFrmGlr-qYR8Y-7-GU/edit#heading=h.nkuoyym8zf2f) (далее просто Pioneers)

Проведены две встечи по Asteroid Rush и Pioneers.

---
@Arteg0r 
Данную задачу можно закрывать - продолжение в следующей серии.

**Comment by Arteg0r** [comment]
BLOCK #24981494


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 400.00000 UTDEV

@Dvarnrock Спасибо!
