### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 6, фокус над поиском решения для коммуникаций

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#18]
@Arteg0r @Dvarnrock 
После предыдущей итерации (https://github.com/u-transnet/Gamedev/issues/16) взял дополнительное время чтобы проанализировать коммуникации внутри игры между игроками и разбавления общей немного сухой механики игры чем-то более новым и современным, позволяющим выстраивать интересные социальные и коммуникационные связи.

Так как идёт фокус на подготовке к последнему этапу обсуждения концепта, работу над SkyWay Planets отложил на другую итерацию.

По итогам итерации концепт документ дополнится видением коммуникационных механик внутри игры, социальной составляющей и т.п. Прогресс будет виден на [борде в Realtimeboards](https://realtimeboard.com/app/board/o9J_kzr93Fs=/)

Длительность итерации 23-28 февраля, рабочих дней - 4.

**Comment by cartoonka** [comment]
BLOCK #24795664

TRANSFER |  
-- | --
From | alexei-postnikov
To | utd-gamedesign
Quantity | 400.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
По итогам постоянных совершенствований и уточнений концепции выявлено центральное направление, обоснование и смысл концепции.

@Arteg0r итерацию можно закрывать.

**Comment by Arteg0r** [comment]
BLOCK #24966133


TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 400.00000 UTDEV

Спасибо!
