### ISSUE TITLE
Работа над презентацией нового концепта (AR Pioneers)

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#19]
@Arteg0r @cartoonka 

Предыдущая итерация[ тут](https://github.com/u-transnet/Gamedev/issues/17).

За два дня 2.03 -- 5.03 (по полной ставке):
1) Доработка питч-документа по проекту AR Pioneers.
2) Подготовка презентации проекта AR Pioneers.
3) Планирование спринта
4) Встречи со смежниками.

**Comment by pkondrashov-ms** [comment]
Block #24956472
From | pkondr1979
To | utd-gamedesign
Quantity | 250.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
По результатам:
1. [Питч](https://docs.google.com/document/d/13RVhQvV2kJXKcIuNSG_dAOkUffFrmGlr-qYR8Y-7-GU/edit#) 
2. Презентация в процессе доработки. Не выкладываю до офиц. показа
3. Done
4. Done - из встречи с Костей "возгорелось пламя" )

@Arteg0r 
Задачу закрываю.

**Comment by Arteg0r** [comment]
BLOCK #25014385


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 250.00000 UTDEV

@Dvarnrock, спасибо!
