### ISSUE TITLE
Координация работ по игровому направлению

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/Gamedev#2]
- найм геймдизайнеров (сформулировать вакансии и звести задачи под них)

- организация работ по описанию глобальной концепции (максимальная/визионерская концепция). Исполнитель - предположительно Дима

- исследовать стратегические движки. Результат - аналитическая записка со списком вариантов, списком источников информации

- исследовать комьюнити модмейкеров Minecraft, результат - аналитическая записка

- получить инструкции по bitshares от Кости

**Comment by Arteg0r** [comment]
BLOCK #22967365
TRANSFER |  
From | arteg0r
To | utd-architect-game
Quantity | 350.00000 UTDEV.SKILL

Работы до 29 декабря 2017 включительно

**Comment by cptn-solo** [comment]
@Arteg0r 
> найм геймдизайнеров (сформулировать вакансии, задачи под них)

ссылки на задачи под найм можно будет в комментах бахнуть по мере их создания

> организация работ по описанию глобальную концепции (максимальная/визионерская концепция). Исполнитель - предположительно Дима

Тоже можно подготовить задачу, и как найдем исполнителя - назначим (ссылку на задачу сюда тоже добавим)

> исследовать стратегические движки. Результат - аналитическая записка со списком вариантов, списком источников информации

спайк надо создать, и сюда ссылку на него. (лейбл question)

**Comment by Arteg0r** [comment]
1. Первоначально я собирался разделить работы между двумя специалистами таким образом, чтобы каждый получил в разработку один игровой режим (а их, напомню, два - стратегический и операционный). В ходе работы над вакансиями я осознал, что мне придется нагрузить вполне сформулированными задачами двух специалистов. А ведь в текущий момент еще на концептуальном уровне остается масса вопросов. 

 Поэтому я принял решение действовать от общего к частному -  сперва взять ведущего специалиста и проработать с ним концепцию и в общих чертах дизайн документ. Чтобы начать проектировать прототип, наших сил должно хватить. А уже на "расширение" игровой  вселенной взять второго человека, или нескольких, но рангом пониже. Все эти размышления нашли отражение в [U-tech - вакансии направления gamedev](https://docs.google.com/document/d/1xthr7w5U3-lA-ARgXwTQaGwLbfxS7gPJKeuEvMWqKcY/edit?usp=sharing). Задачи под вакансии в гитхабе **[здесь](https://github.com/u-transnet/info/issues/53)**

2. Для проработки глобальной или, как мы ее назвали с Костей, максимальной/визионерской концепции, предполагалась привлечь нового участника проекта - Дмитрия. К сожалению, он в этот недельный спринт не подключился к деятельности, и, как стало известно от Наташи, не готов пока с головой нырять в работу (и вообще, лежит с температурой). Пока я возьму ее на себя - попробую набросать тезисы и показать Косте.

3. Еще одной задачей на эту неделю было небольшое исследование стратегических движков. В ходе просеивания данных поисковой выдачи, упоминаний на форумах и гитхабе, я выделил явных фаворитов (список, конечно, не исчерпывающий и может дополняться). Если бы меня просили выделить какой-то вариант, я бы отметил проект на Unity - RTS Engine. Заточенный под стратегии инструментарий, хорошие отзывы о продукте и поддержке, магазин ассетов Юнити под рукой, мультиплатформенность. В общем, [Обзор стратегических движков](https://docs.google.com/document/d/1hEZpQv4krcDdwHqq5cmnS7xWYwi7iq91ldSoja76HFw/edit?usp=sharing)

4. Еще одно экспресс-исследование посвящено модам, модмейкерам и инструментам моддинга Minecraft. Результат исследования выложен здесь [Обзор ресурсов и сообществ модеров Minecraft](https://docs.google.com/document/d/10q-aLLnfGg5RttnlHB5lrIdt_dAuXXd-Yc8EaSyNWRs/edit?usp=sharing). Два основных вопроса, которые я себе задал в ходе переработки информации: 

- нельзя ли обойтись минимальными средствами, набрать по возможности готовых модов и в качестве прототипа настроить свой модпак?
- нельзя ли в качестве стратегического режима доработать мод с глобальной картой jorneymap, либо сделать похожий (и совершенно отказаться от стратегического движка)?

5. Наконец, вчера с Костей разобрались в ассортименте наших токенов и тонкостях работы бюджетных учеток,  а также вместе с Наташей обсудили вопросы менеджерской отчетности и схему подтверждения выплаты вознаграждения (и проверили ее на Наташе :)

**Comment by cptn-solo** [comment]
@Arteg0r 

BLOCK #23102771
CREATE PROPOSAL |  
Proposed operations | Transfer 350.00000 UTDEV from utd-architect-game to arteg0r
BLOCK #23102803
Active approvals to add | cptn-solo
BLOCK #23102795
Active approvals to add | arteg0r

Спасибо!
