### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 7, финализация концепта с учетом всех обсуждений и нововведений

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#20]
@Arteg0r @Dvarnrock 
По итогам обсуждений в последние две итерации концепция Asteroid Rush слегка изменилась в более миролюбивую и кооперационную сторону. По итогам предыдущей итерации (https://github.com/u-transnet/Gamedev/issues/18) документ финализируется и будет готов к финальному обсуждению перед началом подготовки презентации

Длительность итерации с 1 по 6 марта включительно, рабочих дней - 4.

**Comment by cartoonka** [comment]
BLOCK #24961535
TRANSFER |  
From | alexei-postnikov
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
@Arteg0r задачу можно закрывать

**Comment by Arteg0r** [comment]
BLOCK #25284390

TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 500.00000 UTDEV
