### ISSUE TITLE
AR Pioneers - финальная презентация + обсуждения, концепт системы bitKarma

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#21]
@Arteg0r @cartoonka 

Предыдущая итерация [тут](https://github.com/u-transnet/Gamedev/issues/19).

В этой серии:
1. Доработка презентации AR Pionees в финальный вид (+ слайды про социальные взаимодействия и блокчейн).
2. Обсуждение концептов и презентаций Asteroid Rush и Pioneers
3. Питч системы bitKarma (совместно с Алексеем).

6.03-7.03

**Comment by pkondrashov-ms** [comment]
Block #24991380
From | pkondr1979
To | utd-gamedesign
Quantity | 250.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
Результаты следующие:
1) Представил в тестовом виде презентацию AR Pioneers - обсудили и отправили на доработку по фидбеку (в след. задаче). Также приняли решение перевести презентации под Google Презентации.
2) Питч системы bitKarma писал пока один - отправлен на доработку на след неделю.

@Arteg0r 
Закрываем

**Comment by Arteg0r** [comment]
BLOCK #25215861


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 250.00000 UTDEV

@Dvarnrock Спасибо!
