### ISSUE TITLE
Доработка презентации AR Pioneer по результатам тестового показа, питч системы bitKarma, презентация проектов

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#22]
@Arteg0r @cartoonka 

Предыдущая [задача](https://github.com/u-transnet/Gamedev/issues/21).

Мы пилили-пилили и наконец-то выпилили!

После праздников
с 12.03 до 14.03 включительно:
1) Подготовка финальной презентации проекта AR Pioneers для показа в среду (с переносом ее под Google Презентации)
2) Концепт системы bitKarma.
3) Обсуждение презентации (и концепции) Asteroid Rush.
4) Представление проектов в среду 14.03

**Comment by pkondrashov-ms** [comment]
Block #25164711
From | pkondr1979
To | utd-gamedesign
Quantity | 375.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
1) Финальная презентация готова - до самой презентации ссылку сюда не выкладываю.
2) Концепт bitKarma в работе - есть черновик: https://docs.google.com/document/d/1EAQED8ZIg7yOUxKrRntPXQrAXrIi80HUpgkqlWVT9ws/edit
3) Обсуждение Rush и представление концептов перенесли на 20.03

@Arteg0r 
Закрываем, насколько понимаю..

**Comment by Arteg0r** [comment]
BLOCK #25418779

TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 375.00000 UTDEV

**Comment by Arteg0r** [comment]
Спасибо @Dvarnrock
