### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 8, вырабокта стратегии презентации

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#23]
@Arteg0r @Dvarnrock 
По результатам работы над концептом Asteroid Rush (https://github.com/u-transnet/Gamedev/issues/20) переходим к разработке презентации.

В первую очередь хочется найти манеру подачи которая поможет одновременно рассказать ключевые особенности проекта и при этом будет понятна профессионалам в других сверах бизнес без обязательного бэкграунда в геймдеве.

Длительность итерации: 7-14 марта, Рабочих дней - 4 (8-11 выходные)

**Comment by cartoonka** [comment]
BLOCK #25276526

TRANSFER |  
-- | --
From | alexei-postnikov
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
@Arteg0r по результатам мучительной вырабокти концепции презентации был найден правильный подход, задачу можно закрывать.

**Comment by Arteg0r** [comment]
BLOCK #25284412

TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 500.00000 UTDEV
