### ISSUE TITLE
StarWay: Asteroid Rush with coop mode - итерация 9, финализации презентации по новой концептуальной схеме

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#24]
@Arteg0r @Dvarnrock 
По результатам поиска правильной концепции презентации (https://github.com/u-transnet/Gamedev/issues/23) финализируем презентацию для сообщества UT

На выходе будет 10-15 страничная презентация в популярной манере рассказывающая о нашем проекте, для кого мы и почему его делаем, и зачем нам самим это нужно.

Длительность итерации: 15-20 марта, рабочих дней - 4.

**Comment by cartoonka** [comment]
BLOCK #25276720

TRANSFER |  
-- | --
From | alexei-postnikov
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
@Arteg0r 
задачу можно закрывать

**Comment by cartoonka** [comment]
https://docs.google.com/presentation/d/1UQRaHAuDckiIgAlFruaLnUyAlQRfnIJj5hJl3dioGC8/edit?usp=sharing

**Comment by Arteg0r** [comment]
BLOCK #25423901

TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 500.00000 UTDEV

@cartoonka Спасибо!
