### ISSUE TITLE
Финальный этап отбора идей перед презентацией.

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#25]
@Arteg0r @cartoonka 

Предыдущая[ задача](https://github.com/u-transnet/Gamedev/issues/22).

В этом выпуске:

1. Обновление и доработка концепта AR Pioneers. 
2. Создание презентации концепции bitRep. 
3. Обсуждение Asteroid Rush. 
4. Представление проектов.

Сроки: с 15.03 по 20.03

**Comment by pkondrashov-ms** [comment]
Готовы:
Презентация AR Pioneers, Презентация битКарма, проведено обсуждение Asteroid Rush и презентация проектов. Было весело )

@Arteg0r 
Закрываю

**Comment by pkondrashov-ms** [comment]
Забыл приложить:
Block #25357045
From | pkondr1979
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by Arteg0r** [comment]
BLOCK #25563030


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 500.00000 UTDEV

@Dvarnrock Спасибо!
