### ISSUE TITLE
Симулятор развития города с помощью Transnet/SkyWay - итерация 1

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#26]
@Arteg0r @Dvarnrock 
По результатам презентации 20 марта и задачи (https://github.com/u-transnet/Gamedev/issues/24), совместно с @Dvarnrock  приступили к разработке дополненной и улучшенной концепции предыдущих концепций Городов и Планеты

В результате будет презентация и план создания проекта, лучше подходящего под обновленные требования стейкхолдеров.

Длительность итерации - с 21 по 26 марта, рабочих дней - 4

**Comment by cartoonka** [comment]
BLOCK #25454739

TRANSFER |  
-- | --
From | alexei-postnikov
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
@Arteg0r @Dvarnrock 
по результатам собрания в пятницу, 23-03, договорились что сделаю к понедельнику 2-3 варианта визуализации проекта и как мы это будем делать

**Comment by cartoonka** [comment]
@Arteg0r 
по результатам обсуждения во вторник, 27 марта, задачу можно закрывать.

**Comment by Arteg0r** [comment]
BLOCK #25617653


TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 500.00000 UTDEV

@cartoonka Спасибо
