### ISSUE TITLE
Обсуждение результатов презентации, доработка SkyWay: Cities по результатам

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#27]
@Arteg0r @cartoonka

Предыдущая [задача](https://github.com/u-transnet/Gamedev/issues/25).

В этой задаче:
1) Обсуждение результатов презентации
2) Доработка концепта по SkyWay: Cities
3) Создание презентации SkyWay: Cities Mk2

Срок 21.03 - 26.03

**Comment by pkondrashov-ms** [comment]
Block #25455143
From | pkondr1979
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
Черновик презентации готов, обсуждение провели.

@Arteg0r 
Закрываем

**Comment by Arteg0r** [comment]
BLOCK #25789675


TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 500.00000 UTDEV

@Dvarnrock Спасибо!
