### ISSUE TITLE
Симулятор построения сети TransNet в раззных уголках планеты - итерация 1

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#28]
@Arteg0r @Dvarnrock 
По результатам обновления требования и пожеланий от заказчика слегка меняется концепция.
В данной итерации ведем диалог с заказчиком об уточнении требований и вариантов визуализации и работы симулятора.

На выходе должен получиться финальный вид презентации обновленной версии симулятора и понимание какими средствами и инструментами этого можно добиться.

Длительность итерации - 27-30 марта. Рабочих дней - 4.

**Comment by Arteg0r** [comment]
@cartoonka Скилл нужно отправить

**Comment by cartoonka** [comment]
сделаю

**Comment by cartoonka** [comment]
BLOCK #25793906

TRANSFER |  
-- | --
From | alexei-postnikov
To | utd-gamedesign
Quantity | 500.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
@Arteg0r 
презентацию закончили совместными усилиями, задачу можно закрывать

**Comment by Arteg0r** [comment]
BLOCK #25848590


TRANSFER |  
-- | --
From | utd-gamedesign
To | alexei-postnikov
Quantity | 500.00000 UTDEV

@cartoonka Спасибо!
