### ISSUE TITLE
Transnet: World - Обсуждение концепции, доработка презентации, список требований

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#29]
@Arteg0r @cartoonka 

Предыдущая [задача](https://github.com/u-transnet/Gamedev/issues/27).

На этой неделе:

- Обсуждаем концепцию развития проекта SkyWay: Cities в рамках выставленных требований
- Пишем список требований и предварительный список фич
- Доработка презентации
- Поиск технических решений

Рабочие дни 27.03 - 30.03
28.03 с нагрузкой 50% (с округлением в > по скиллу)

**Comment by pkondrashov-ms** [comment]
Block #25676497
From | pkondr1979
To | utd-gamedesign
Quantity | 440.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
Концепция готова.
Список требований и предварительный список фич:
https://u-trans.atlassian.net/wiki/spaces/TG/pages/116948997/
Презентация доработана до версии Mk2.

Закрываем.

**Comment by Arteg0r** [comment]
BLOCK #25851745

TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 440.00000 UTDEV

@Dvarnrock Спасибо!
