### ISSUE TITLE
Координация работ по игровому направлению

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/Gamedev#3]
Коллеги @kkrupovich @nat-brit !

Предыдущий отчет [тут](https://github.com/u-transnet/Gamedev/issues/2)

Эта итерация короткая  - возьму 3 дня, на 40%. Я, как и Костя, приглядываю за мелким. В этом спринте я планирую:

- распространить информацию о вакансии геймдизайнера (объявления в соцсетях, группа "вакансии геймдев" в вк, через личные обращения к знакомым)
- концепция верхнего уровня (максимальная/визионерская), тезисно (если Лиза подключится, то вместе с ней)
- исследовать стратегические проекты на движке Годот (который приглянулся Косте после [обзора движков](https://docs.google.com/document/d/1hEZpQv4krcDdwHqq5cmnS7xWYwi7iq91ldSoja76HFw/edit))
- сформулировать функциональные требования к прототипу, обсудить их с Костей (потому что при обсуждении [этой концепции](https://docs.google.com/document/d/11Sk2VMlI0M9kjpFsFv1ZITH34eyoFcKSbHnLl5fOxFE/edit) отметил, что наши видения отличаются)

**Comment by cptn-solo** [comment]
@Arteg0r полагаю, можно закидывать скилл, до конца выходных.
Единственное, вакансию я бы все же зафиксировал по аналогии (в info есть задачи, тэг HR + проект (формирование команды)

**Comment by Arteg0r** [comment]
@kkrupovich Да, Костя, зафиксировать вакансию по нашим правилам - часть задачи.

**Comment by Arteg0r** [comment]
BLOCK #23408293
TRANSFER |
From | arteg0r
To | utd-architect-game
Quantity | 210.00000 UTDEV.SKILL

Работы до 12 января включительно

**Comment by Arteg0r** [comment]
Коллеги @kkrupovich @nat-brit 

Делюсь промежуточными итогами, задачу не закрываю. Мне нужно подзарядить свою концептуальную пушку :) К понедельнику подготовлю отчет по задаче, тогда же ее и закроем.

- мероприятия по продвижению [вакансии](https://github.com/u-transnet/info/issues/53) я решил осуществлять в понедельник, чтобы получить больше внимание френдлент, чем его бывает в конце недели перед выходными.
- обзор стратегических игр на Годот готов (разумеется, будет пополняться, в случае встречи с новыми хорошими примерами). Отобрал любопытные варианты, [смотрите главу в уже известном документе Обзор стратегических движков](https://docs.google.com/document/d/1hEZpQv4krcDdwHqq5cmnS7xWYwi7iq91ldSoja76HFw/edit#heading=h.p6x99zp0xnrt)
- драфт визионерской концепции/манифеста в самом начале уже известного документа [Концепция игры TRANSNET SPACE](https://docs.google.com/document/d/11Sk2VMlI0M9kjpFsFv1ZITH34eyoFcKSbHnLl5fOxFE/edit?usp=sharing)
- [драфт списка требований к прототипу](https://docs.google.com/document/d/1OpifdQG-QijTVM6hBsykD7NuHINYavPw3FnZAgfqfNE/edit?usp=sharing). Кинул Косте созвон по нему в понедельник утром

Помимо этого я договорился с Алексеем о собеседовании потенциального кандидата по вакансии Ведущий геймдизайнер. Ожидаю разговор сегодня.

**Comment by cptn-solo** [comment]
@Arteg0r 

> Мероприятия по продвижению вакансии 

[Планирую](https://github.com/u-transnet/info/issues/52) в понедельник тоже заняться вакансиями, кстати. И не забывайте про то, что готов [перевод](https://github.com/u-transnet/info/issues/55) fullstack веб-разработчика и его тоже можно ~~шлифовать и~~ куда-то пристраивать

> Отобрал любопытные варианты

[откомментил](https://docs.google.com/document/d/1hEZpQv4krcDdwHqq5cmnS7xWYwi7iq91ldSoja76HFw/edit?disco=AAAABcrUcxg) 👍 (в конце оставил один скромный комментарий). 

> драфт визионерской концепции/манифеста
> драфт списка требований к прототипу

Открыл документ, начал читать, и понял, что нам надо в свои планы и отчеты, @nat-brit , @Arteg0r , обязательно включать анализ труда руководителей смежных направлений :)) - потому что сил и времени на это тратится довольно много. Кроме того, если этим заниматься факультативно, @alecvert , то мы перестаем понимать смежников (я уж не говорю о том, что мы физически не в состоянии вникать в ход работ _всех_ направлений DAC.

**Comment by Arteg0r** [comment]
Коллеги, @kkrupovich @nat-brit , предлагаю завершать данную итерацию. Итоги по ней:

- [Вакансия](https://github.com/u-transnet/info/issues/53) расшарена, собираю фидбек от первых кандидатов. Установлена связь с Ильей, кандидат @alecvert . Собираюсь опубликовать вакансию на [app2top](http://app2top.ru/). 
- Кто еще не видел, [Обзор стратегических движков](https://docs.google.com/document/d/1hEZpQv4krcDdwHqq5cmnS7xWYwi7iq91ldSoja76HFw/edit#heading=h.p6x99zp0xnrt)
- визионерская концепция/манифест здесь - [Концепция игры TRANSNET SPACE](https://docs.google.com/document/d/11Sk2VMlI0M9kjpFsFv1ZITH34eyoFcKSbHnLl5fOxFE/edit?usp=sharing). С прошлого, промежуточного отчета она почти не изменилась. Предлагаю пока оставить ее в таком виде, расширяя по мере возникновения идей у членов команды. Отдельного времени на нее больше не выделять.
- работая параллельно над манифестом и требованиями к прототипу, а потом общаясь с командой в чате, мне стало понятно следующее. Придумать фичи сейчас гораздо проще, чем решить, каким минимальным набором характеристик должен обладать прототип. Поэтому предлагаю включить работу [с данным документом](https://docs.google.com/document/d/1OpifdQG-QijTVM6hBsykD7NuHINYavPw3FnZAgfqfNE/edit?usp=sharing), а также его обсуждения в следующий спринт.

Несколько слов про вчерашний скайп чат. Было приятно всех услышать и познакомиться, равно как и обсудить с командой широкий круг вопросов. И хотя я бы предпочел сосредоточиться на прототипе :) я склонен думать, что вчерашнее общение было всем полезно. Вот некоторые темы, касающиеся игры, которые мы затронули:
- что мы делаем симулятор корпорации и моделируем войны стэкхолдеров
- что мы, в общем-то, можем пока отказаться от операционного режима
- что действие игры может проходить не только на Земле, но и на Марсе, других планетах 
- мы поспорили, сколько может быть рилмов (игровых миров), но не сошлись на едином мнении
(форки это или копии нашего блокчейна с настройками)
- что рилм имеет также демонстрационный смысл для инвесторов и заказчиков
- что мы не забываем про игровую терминологию, например классы персонажей
- что надо узнать больше о лицензии майнкрафта и о существовании "опенкрафта"
- что проверка интеграции майнкрафта и блокчейна требует отдельной исследовательской задачи
- узнали о том, как можно продавать виртуальные земли за токены, чтобы потом построить там Сан-Франциско (проект Decentraland)

**Comment by cptn-solo** [comment]
@Arteg0r 
> каким минимальным набором характеристик должен обладать прототип. 

немного добавил в документ, потом поймал себя на том, что начал углубляться в экономику и политику игры. Понял, что нужно идти в Концепцию и править/добавлять там. Открыл концепцию, и закрыл концепцию :)

> мы поспорили, сколько может быть рилмов (игровых миров), но не сошлись на едином мнении (форки это или копии нашего блокчейна с настройками)

мне кажется, что если по крайней мере наш собственный оригинальный бранч назвать transnet expanse - и у нас будет столько планет, астероидов, станций и звездных систем с разными генезисами, токенами базового актива и прочей атрибутикой, что вам и не снилось. Они еще войны потом между собой устраивать начнут, колонии эти. А почти сразу после войн - додумаются до нескольких разумных космических рас :) Но сколько их будет на самом деле - решит лишь степень потребности в них у нас и у сообщества.

> что надо узнать больше о лицензии майнкрафта и о существовании "опенкрафта"

Только сейчас вспомнил, что видел в стиме и других магазинах приложений игры, очень похожие на майнкрафт (на "движке", неотличимом от майнкрафта на первый взгляд). Надо исследовать вопрос с их лицензией. 
Также к вопросу о монетизации - есть очень много игровых серверов и рынков вокруг них (minecraft). Не думаю, что это проблема. 

> что проверка интеграции майнкрафта и блокчейна требует отдельной исследовательской задачи

@codename-art коллега, не хочешь заняться? я если что помогу. Но это вторым приоритетом - чтобы было что интегрировать - нам как раз-таки и нужен [симулятор](https://github.com/u-transnet/transnet-simulator)

**Comment by cptn-solo** [comment]
@Arteg0r 
> Коллеги, @kkrupovich @nat-brit , предлагаю завершать данную итерацию. Итоги по ней:

BLOCK #23599999

CREATE PROPOSAL |  Expiration time | January 18, 2018, 3:09:53 AM
Proposed operations | Transfer 210.00000 UTDEV from utd-architect-game to arteg0r

@Arteg0r  @nat-brit @alecvert транзакция ожидает подтверждения на **utd-architect-game**

Надо следующую задачу с этой связать обязательно
