### ISSUE TITLE
Координация работ по игровому направлению №3 (15-19.01)

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/Gamedev#4]
@kkrupovich @nat-brit 

Предыдущая задача [здесь](https://github.com/u-transnet/Gamedev/issues/3)

В эту итерацию я собираюсь взять 4 дня по 40% (с вашего позволения, включу в один из них все коммуникации за понедельник и вторник) для следующих дел:
- отбора и собеседования кандидатов на вакансию Ведущий геймдизайнер. **На выходе**: решение по имеющимся в наличии кандидатам.
- продолжить уточнение требований к MVP (не без участия Кости и остальной команды), начало [положено тут](https://docs.google.com/document/d/1OpifdQG-QijTVM6hBsykD7NuHINYavPw3FnZAgfqfNE/edit?ts=5a5e6c2e#heading=h.4v3fabyy0mik). **На выходе**: уточненнный, расширенный документ 
- хочу стартовать еще один документ, который, надеюсь, поможет увидеть цельность и ценность прототипа, и который будет отправной точкой для создания дизайн-документа. хочу сделать общее описание процесса работы прототипа, более художественное, под заголовком в духе "стратегическая игра Войны стэкхолдеров". Не рассматривая при этом операционный режим вовсе. **На выходе** из итерации будет небольшой набросок.

Как и обещал ранее, сообщаю о **январском плане работ** в игровом направлении:

- определиться с кандидатом на позицию Ведущий геймдизайнер
- понять границы прототипа, отобрать требования к нему
- стартовать работы над дизайн-документом
- определиться с дальнейшим наймом сотрудников игрового направления

**Comment by Arteg0r** [comment]
BLOCK #23642076
TRANSFER |
From | arteg0r
To | utd-architect-game
Quantity | 280.00000 UTDEV.SKILL

Работы на неделе 15-19 января, 4 дня. Отчет по задаче - к 21 января.

**Comment by cptn-solo** [comment]
@Arteg0r предлагаю как-то нумеровать задачи (может, номер недели использовать, или просто номер по порядку, как мы втыкали - "Итерация N.  бла бла бла"?)

**Comment by Arteg0r** [comment]
@kkrupovich @nat-brit 

Итак, коллеги, итерация несколько растянулась из-за наплыва соискателей )

Ее итоги:
- Получены и рассмотрены заявки от 9 соискателей на должность ведущего геймдизайнера.  Проведены 3 собеседования, одна заявка отклонена до собеседования. На текущий момент выделил для себя одного сильного кандидата. План на ближайшую итерацию: проведу 4-5 собеседований, к началу следующей недели планирую закрыть вакансию.
- Весьма продуктивно обсудили с Костей [документ по требованиям к прототипу](https://docs.google.com/document/d/1OpifdQG-QijTVM6hBsykD7NuHINYavPw3FnZAgfqfNE/edit?ts=5a5e6c2e#heading=h.4v3fabyy0mik). Вопросы остались, копятся для следующего обсуждения.
- Весьма сырой, впрочем, как и ожидалось в этот спринт, [документ](https://docs.google.com/document/d/1n-j0-jPrQTBjvK2CjBaI8d9G_rNYLRMhu_sqI-qH9fk/edit?usp=sharing), посвященный художественному осмыслению прототипа

Прошу закрыть задачу. Спасибо!

**Comment by cptn-solo** [comment]
@Arteg0r @nat-brit коллеги, транзакция ожидает подтверждения на учетке **utd-architect-game**:

BLOCK #23812582

CREATE PROPOSAL |  
-- | --
Expiration time | January 25, 2018, 1:20:07 PM
Proposed operations | Transfer 280.00000 UTDEV from utd-architect-game to arteg0r
