### ISSUE TITLE
Подбор сотрудника на должность Ведущий геймдизайнер

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/Gamedev#5]
@kkrupovich @nat-brit 

Предыдущая задача [здесь](https://github.com/u-transnet/Gamedev/issues/4)

Коллеги, сейчас занимаюсь только собеседованиями и изучением материалов, предоставленных соискателями. Закладываю на это три дня - 24-25-26. О других задачах сообщу отдельно.

Выбор кандидата (или даже двух) сделаю в начале следующей недели.

**Comment by Arteg0r** [comment]
BLOCK #23842607
TRANSFER |
From | arteg0r
To | utd-architect-game
Quantity | 210.00000 UTDEV.SKILL

Решение по выбору кандидата (-ов) сделаю 29 января.

**Comment by Arteg0r** [comment]
Коллеги @kkrupovich @nat-brit

Отобраны два кандидата: 

- Алексей Постников (19 лет в геймдизайне и продюсировании игр, город Калининград) 
- Павел Кондрашов (15 лет в геймдизайне, город Краснодар)

[Вакансию ](https://github.com/u-transnet/info/issues/53) закрыл.

Прошу подтвердить закрытие итерации.

**Comment by cptn-solo** [comment]
@Arteg0r @nat-brit @alecvert предложил транзакцию на **utd-architect-game**
BLOCK #24005433

CREATE PROPOSAL |  
-- | --
Expiration time | February 1, 2018, 6:32:54 AM
Proposed operations | Transfer 210.00000 UTDEV from utd-architect-game to arteg0r

**Comment by cptn-solo** [comment]
@cartoonka принят, бюджетная позиция **utd-gamesesign**: 
- макс. ставка эквивалент 2500 USD/мес.
- стандартная [схема роста](https://github.com/u-transnet/info/wiki/2.1.-%D0%A0%D0%BE%D1%81%D1%82-%D0%B2-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B5)
- начинаем с 80% - эквивалент 2000USD/мес., эквивалент **100**USD/день

BLOCK #24025410

CREATE PROPOSAL |  
-- | --
Expiration time | February 1, 2018, 11:14:31 PM
Proposed operations | Transfer 2,000.00000 UTDEV.SKILL from ut-dev to alexei-postnikov

BLOCK #24025505

UPDATE PROPOSAL |  
-- | --
Fee paying account | arteg0r
Proposal object id | 1.10.8040

BLOCK #24025434

UPDATE PROPOSAL |  
-- | --
Fee paying account | cptn-solo
Proposal object id | 1.10.8040

**Comment by Arteg0r** [comment]
@Dvarnrock  принят, бюджетная позиция utd-gamesesign:

макс. ставка эквивалент 2500 USD/мес.
стандартная схема роста
начинаем с 80% - эквивалент 2000USD/мес., эквивалент 100USD/день

BLOCK #24025581

CREATE PROPOSAL |  
-- | --
Expiration time | February 1, 2018, 11:23:01 PM
Proposed operations | Transfer 2,000.00000 UTDEV.SKILL from ut-dev to pkondr1979

BLOCK #24025611

UPDATE PROPOSAL  |  
-- | --
Fee paying account  |  cptn-solo
Proposal object id  |  1.10.8041

BLOCK #24025588

UPDATE PROPOSAL |  
-- | --
Fee paying account | arteg0r
Proposal object id | 1.10.8041
