### ISSUE TITLE
Координация работ по игровому направлению №4

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/Gamedev#6]
@kkrupovich @nat-brit

[Поиск геймдизайнеров завершился тут](https://github.com/u-transnet/Gamedev/issues/5)

Задачи на 30, 31 января (сжигаю остаток скила с нагрузкой 40%):

- обсудить с Костей вопросы по требованиям к прототипу
- менеджмент учеток и токенов для игрового направления, ликбез Кости
- инструктаж новых сотрудников по схеме работы, опрерациям в блокчейне, заведение необходимых учеток, другие орг.вопросы

BLOCK #23991317
TRANSFER |
From | arteg0r
To | utd-architect-game
Quantity | 140.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
@Arteg0r @nat-brit 
> менеджмент учеток и токенов для игрового направления, ликбез Кости

Надо будет вместе подумать про токены направлений. Мы с @Arteg0r близко подобрались к решению вопроса, но не решились :)

@alecvert  вернешься - с тобой вместе решим.

**Comment by nat-brit** [comment]
@kkrupovich  Запланируй, плиз, созвон по этому поводу, этот вопрос хорошо бы обсудить побыстрее.

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert 
> @kkrupovich Запланируй, плиз, созвон по этому поводу, этот вопрос хорошо бы обсудить побыстрее.

Созвон это хорошо, но под созвон неплохо бы подготовить варианты, из которых мы вибираем. Это отдельная User Story - как именно лучше токенизировать работу в условиях нескольких инвесторов, нескольких операторов (типа U-Tech) и нескольких исполнителей (типа UT-DEV с токенами UTDEV+SKILL). Поэтому у нас теперь есть [эпик в jira](https://u-trans.atlassian.net/browse/UT-15), и нужно собрать истории от каждой роли. Историю разработчика я [начал](https://u-trans.atlassian.net/browse/UT-16). Надо определиться кто еще может быть заинтересованным участником этого процесса (инвестор, руководитель направления, кто еще ?)

**Comment by Arteg0r** [comment]
@nat-brit @kkrupovich 
Закрыл итерацию. На выходе:

- проведена очная встреча с @kkrupovich, в ходе которой мы разобрали появившиеся вопросы по требованиям к прототипу, а также разобрались с учетками игрового направления
- выполнен инструктаж новых сотрудников по схеме работы, операциям в блокчейне. Заведены необходимые учетки, решены орг. вопросы. 
- проведено вступительное собрание с новыми сотрудниками при участии @kkrupovich, на котором обсудили миссию компании U-Tech и проекта Transnet, задачи игрового направления, взаимодействие со смежниками, ответили на вопросы новых сотрудников
- новые сотрудники игрового направления включены в работу

**Comment by cptn-solo** [comment]
@Arteg0r 
BLOCK #24028366

CREATE PROPOSAL |  
-- | --
Review period begin | —
Expiration time | February 2, 2018, 1:42:31 AM
Proposed operations | Transfer 140.00000 UTDEV from utd-architect-game to arteg0r
