### ISSUE TITLE
Питч проекта №1 StarWay: Asteroid rush

### ISSUE THREAD

**Issue by cartoonka** [u-transnet/Gamedev#8]
@Dvarnrock @Arteg0r 

Обсудить и написать питч проекта номер 1.

Рабочее название StarWay: Asteroid Rush

В результате:

- Проведено обсуждение потенциальных идей.
- Выделены рабочие гипотезы.
- Превращены в документы.

Ожидаемый результат - питч документ в гуглдоках, ссылка будет добавлена в задачу в конце работ.

Даты работ 1-5 февраля.  Рабочих дней - 3.

**Comment by cartoonka** [comment]
BLOCK #24046499
TRANSFER |  
From | alexei-postnikov
To | utd-gamedesign
Quantity | 300.00000 UTDEV.SKILL

**Comment by cartoonka** [comment]
По изначальной идее, обсужденной в четверг, представлен питч документ
(доступен по [ссылке](https://docs.google.com/document/d/1xTEUg3d2MQttTrY6YGm-40yQ_MunlVJbyI0qQX4GBE8/edit?usp=sharing))

- В целом концепция принята
- Уже в докмент добавлены направления и вопросы для дальнейшего улучшения документа 
- Внесены несколько комментариев и направлений для изучения

Дальнейшее развитие - насыщение документа новые темами, ответами на вопросы и перевод его в состояние концепт документа.

**Comment by Arteg0r** [comment]
BLOCK #24191680

TRANSFER |  
From | utd-gamedesign
To | alexei-postnikov
Quantity | 300.00000 UTDEV
