### ISSUE TITLE
Доработка кратких концептов

### ISSUE THREAD

**Issue by pkondrashov-ms** [u-transnet/Gamedev#9]
@Arteg0r @cartoonka 

Данная задача продолжение [предыдущей](https://github.com/u-transnet/Gamedev/issues/7).

В этой итерации:

- Провести обсуждение концептов
- Доработать и финализировать концепты проектов SkyWay: Simply (дать другое рабочее название) и SkyWay: Asteroids (на Алексее)
- Совместная работа над черновиком концепта SkyWay: Cryptoprogressor
- Обсуждение доработанного концепта SkyWay: Cryptoprogressor

В результате итерации должны появится три финальных концепта с учетом пожеланий и новых идей. После эти документы станут основой расширенных гейм-дизайнерских концептов.

Время на задачу: 6.02 - 8.02 включительно

**Comment by pkondrashov-ms** [comment]
Block #24209585
Transfer
From | pkondr1979
To | utd-gamedesign
Quantity | 300.00000 UTDEV.SKILL

**Comment by pkondrashov-ms** [comment]
Результаты задачи:

Доработан краткий-концепт документ по проекту SkyWay: Cities (бывший Simply SkyWay).

Проведена встреча с Натальей и Петром - по результатам возникли новые идеи по фокусированию проекта и использованию блок-чейн технологий в игре.

Проведен ресерч по концепту SkyWay: Cryptoprogressors - по результатам работы и совместного обсуждения концепт отложен.

@Arteg0r - Можно закрывать.

**Comment by Arteg0r** [comment]
BLOCK #24368902

TRANSFER |  
-- | --
From | utd-gamedesign
To | pkondr1979
Quantity | 300.00000 UTDEV

@Dvarnrock, cпасибо!
